package app.botdrop.ops;

public enum FixAction {
    ENSURE_GATEWAY_OBJECT,
    ENSURE_GATEWAY_MODE_LOCAL,
    ENSURE_GATEWAY_AUTH_TOKEN,
    ENSURE_DEFAULT_MODEL_PRIMARY,
    ENSURE_CHANNEL_PLUGIN_ENTRIES
}
